/**
 * Image-input capability lookup shared by the composer picker, the auto model
 * selection, and relay profile writing.
 *
 * The wire model catalog (`sessions.models`) drops each model’s
 * `inputModalities`, so capability cannot be read back from the harness. It is
 * resolved from the hard-coded vision table below instead, derived from the
 * bundled pi-ai provider catalog (@earendil-works/pi-ai
 * dist/providers/data/*.json — entries whose `input` includes `"image"`),
 * plus the user’s provider sheet and the DeepSeek vision variant. Matching
 * reuses the capacity-table normalization (provider prefixes, variant tags,
 * case and separators are all ignored), and ids whose name carries a
 * `vision` token remain permissively accepted as before. A wrong positive
 * only moves the rejection from admission to the provider’s own error, while
 * a wrong negative silently breaks image prompts — so both channels stay
 * permissive.
 */
import { lookupCandidates, slugKey } from './model-capacity.js'

const VISION_MODEL_IDS: readonly string[] = [
  'auto',
  'auto-beta',
  'claude-3-5-haiku',
  'claude-3-haiku',
  'claude-3-opus',
  'claude-3-sonnet',
  'claude-fable-5',
  'claude-fable-latest',
  'claude-haiku-4-5',
  'claude-haiku-4-5-20251001',
  'claude-haiku-latest',
  'claude-opus-4',
  'claude-opus-4-1',
  'claude-opus-4-1-20250805',
  'claude-opus-4-5',
  'claude-opus-4-5-20251101',
  'claude-opus-4-6',
  'claude-opus-4-7',
  'claude-opus-4-8',
  'claude-opus-4.7-fast',
  'claude-opus-4.8-fast',
  'claude-opus-5',
  'claude-opus-5-fast',
  'claude-opus-latest',
  'claude-sonnet-4',
  'claude-sonnet-4-5',
  'claude-sonnet-4-5-20250929',
  'claude-sonnet-4-6',
  'claude-sonnet-5',
  'claude-sonnet-latest',
  'deep-research-max-preview-04-2026',
  'deep-research-preview-04-2026',
  'deepseek-v4-flash-vision-exp',
  'devstral-small-2',
  'free',
  'fugu-ultra',
  'gemini-2.5-flash',
  'gemini-2.5-flash-lite',
  'gemini-2.5-pro',
  'gemini-2.5-pro-preview',
  'gemini-2.5-pro-preview-05-06',
  'gemini-3-flash',
  'gemini-3-flash-preview',
  'gemini-3-pro-image',
  'gemini-3-pro-preview',
  'gemini-3.1-flash-lite',
  'gemini-3.1-flash-lite-preview',
  'gemini-3.1-pro-preview',
  'gemini-3.1-pro-preview-customtools',
  'gemini-3.5-flash',
  'gemini-3.5-flash-lite',
  'gemini-3.6-flash',
  'gemini-3.7-flash',
  'gemini-flash-latest',
  'gemini-flash-lite-latest',
  'gemini-pro-latest',
  'gemma-3-12b-it',
  'gemma-3-27b-it',
  'gemma-4-26b-a4b-it',
  'gemma-4-26b-a4b-it:free',
  'gemma-4-31b',
  'gemma-4-31b-it',
  'gemma-4-31b-it:free',
  'GLM-4.5V',
  'glm-4.6v',
  'glm-4.6v-flash',
  'glm-5.3',
  'glm-5.3-flash',
  'glm-5v-turbo',
  'gpt-4-turbo',
  'gpt-4.1',
  'gpt-4.1-mini',
  'gpt-4.1-nano',
  'gpt-4o',
  'gpt-4o-2024-05-13',
  'gpt-4o-2024-08-06',
  'gpt-4o-2024-11-20',
  'gpt-4o-mini',
  'gpt-4o-mini-2024-07-18',
  'gpt-5',
  'gpt-5-chat-latest',
  'gpt-5-codex',
  'gpt-5-mini',
  'gpt-5-nano',
  'gpt-5-pro',
  'gpt-5.1',
  'gpt-5.1-chat',
  'gpt-5.1-codex',
  'gpt-5.1-codex-max',
  'gpt-5.1-codex-mini',
  'gpt-5.1-instant',
  'gpt-5.1-thinking',
  'gpt-5.2',
  'gpt-5.2-chat',
  'gpt-5.2-codex',
  'gpt-5.2-pro',
  'gpt-5.3-chat',
  'gpt-5.3-codex',
  'gpt-5.4',
  'gpt-5.4-mini',
  'gpt-5.4-nano',
  'gpt-5.4-pro',
  'gpt-5.5',
  'gpt-5.5-pro',
  'gpt-5.6-luna',
  'gpt-5.6-luna-pro',
  'gpt-5.6-sol',
  'gpt-5.6-sol-pro',
  'gpt-5.6-terra',
  'gpt-5.6-terra-pro',
  'gpt-chat-latest',
  'gpt-latest',
  'gpt-mini-latest',
  'grok-4.1-fast-non-reasoning',
  'grok-4.1-fast-reasoning',
  'grok-4.20',
  'grok-4.20-multi-agent',
  'grok-4.20-multi-agent-beta',
  'grok-4.20-non-reasoning',
  'grok-4.20-non-reasoning-beta',
  'grok-4.20-reasoning',
  'grok-4.20-reasoning-beta',
  'grok-4.3',
  'grok-4.5',
  'grok-4.6',
  'grok-build-0.1',
  'grok-latest',
  'inkling',
  'inkling-small',
  'interfaze-beta',
  'k3',
  'k3-256k',
  'kimi-for-coding',
  'kimi-for-coding-highspeed',
  'kimi-k2.5',
  'kimi-k2.6',
  'kimi-k2.7-code',
  'kimi-k2.7-code-highspeed',
  'kimi-k2p6',
  'kimi-k2p6-fast',
  'kimi-k2p6-turbo',
  'kimi-k2p7-code',
  'kimi-k2p7-code-fast',
  'kimi-k3',
  'kimi-latest',
  'labs-devstral-small-2512',
  'llama-3.2-11b-vision-instruct',
  'llama-3.2-90b-vision-instruct',
  'llama-4-maverick',
  'llama-4-scout',
  'llama-4-scout-17b-16e-instruct',
  'magistral-medium',
  'magistral-small',
  'mimo-v2-omni',
  'mimo-v2.5',
  'mimo-v2.5-pro',
  'minimax-m3',
  'ministral-14b',
  'ministral-14b-2512',
  'ministral-3b-2512',
  'ministral-8b-2512',
  'mistral-large-2512',
  'mistral-large-3',
  'mistral-large-latest',
  'mistral-medium',
  'mistral-medium-2505',
  'mistral-medium-2508',
  'mistral-medium-2604',
  'mistral-medium-3',
  'mistral-medium-3-5',
  'mistral-medium-3.1',
  'mistral-medium-latest',
  'mistral-small',
  'mistral-small-2506',
  'mistral-small-2603',
  'mistral-small-3.2-24b-instruct',
  'mistral-small-4-119b-2603',
  'mistral-small-latest',
  'muse-spark-1.1',
  'nemotron-3-nano-omni-30b-a3b-reasoning',
  'nemotron-3-nano-omni-30b-a3b-reasoning:free',
  'nemotron-nano-12b-v2-vl',
  'nemotron-nano-12b-v2-vl:free',
  'nex-n2-mini',
  'nex-n2-pro',
  'nova-2-lite',
  'nova-lite',
  'nova-pro',
  'o1',
  'o1-pro',
  'o3',
  'o3-deep-research',
  'o3-pro',
  'o4-mini',
  'o4-mini-deep-research',
  'o4-mini-high',
  'pixtral-12b',
  'pixtral-large-latest',
  'qwen-3.8-max',
  'qwen-3.8-max-preview',
  'qwen3-235b-a22b-thinking',
  'qwen3-vl-235b-a22b-instruct',
  'qwen3-vl-235b-a22b-thinking',
  'qwen3-vl-30b-a3b-instruct',
  'qwen3-vl-30b-a3b-thinking',
  'qwen3-vl-32b-instruct',
  'qwen3-vl-8b-instruct',
  'qwen3-vl-8b-thinking',
  'qwen3-vl-instruct',
  'qwen3-vl-thinking',
  'Qwen3.5-122B-A10B',
  'Qwen3.5-27B',
  'Qwen3.5-35B-A3B',
  'Qwen3.5-397B-A17B',
  'Qwen3.5-9B',
  'qwen3.5-flash',
  'qwen3.5-flash-02-23',
  'qwen3.5-plus',
  'qwen3.5-plus-02-15',
  'qwen3.5-plus-20260420',
  'Qwen3.6-27B',
  'Qwen3.6-35B-A3B',
  'qwen3.6-flash',
  'qwen3.6-plus',
  'qwen3.7-plus',
  'qwen3p7-plus',
  'reka-edge',
  'seed-1.6',
  'seed-1.6-flash',
  'seed-1.8',
  'seed-2.0-lite',
  'seed-2.0-mini',
  'Step-3.7-Flash',
]

const VISION_TABLE: ReadonlySet<string> = new Set(VISION_MODEL_IDS.map(slugKey))

export function supportsImageInput(modelId: string): boolean {
  const trimmed = modelId.trim()
  if (trimmed === '') return false
  // Naming-convention fallback: explicit vision-token ids not (yet) listed in
  // the table still admit images.
  if (trimmed.toLowerCase().includes('vision')) return true
  for (const candidate of lookupCandidates(trimmed)) {
    if (VISION_TABLE.has(slugKey(candidate))) return true
  }
  return false
}

